# Generated by Django 5.1.15 on 2026-09-13 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('company', models.CharField(db_index=True, max_length=180)),
                ('location', models.CharField(blank=True, db_index=True, max_length=120)),
                ('description', models.TextField()),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=8)),
                ('experience_min', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(db_index=True, default='manual', max_length=60)),
                ('external_url', models.URLField(blank=True)),
                ('external_job_id', models.CharField(blank=True, max_length=120, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at', '-collected_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_job_id__isnull', False)), fields=('source', 'external_job_id'), name='unique_external_job_per_source'), models.CheckConstraint(condition=models.Q(('salary_max__isnull', True), ('salary_min__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='job_salary_range_valid')],
            },
        ),
    ]
