# Generated by Django 5.1.15 on 2026-09-13 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_external_job_per_source',
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('external_job_id__isnull', False), models.Q(('external_job_id', ''), _negated=True)), fields=('source', 'external_job_id'), name='unique_external_job_per_source'),
        ),
    ]
