# Generated by Django 5.1.15 on 2026-09-13 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('professional_headline', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('desired_job_titles', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('minimum_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=30)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('preferred_technologies', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('maximum_salary__isnull', True), ('minimum_salary__isnull', True), ('maximum_salary__gte', models.F('minimum_salary')), _connector='OR'), name='candidate_salary_range_valid')],
            },
        ),
    ]
